splash = false

preload = ~/Pictures/wallpaper/Shishkin,_Ivan_-_Morning_in_a_Pine_Forest.jpg

wallpaper {
    monitor = DP-1
    path = ~/Pictures/wallpaper/Shishkin,_Ivan_-_Morning_in_a_Pine_Forest.jpg
}

